### ISSUE TITLE
Modification dissappear when recovering ship with storypoint

### ISSUE THREAD

**Issue by Versalkul** [scardwell15/ExoticaTechnologies#1]
I noticed that modifications are gone when recovering a ship (found in the world) with story points. 
I play with Starpocalypse, Unknown skies and Adjusted Sector (all at default settings) so it could be an mod incompatibility.
I appended a save game file as an example. 
If the Sunder "ISS Faraway and Gone" is recovered using a story-point, it has no modifications.
When scanning the not yet recovered ship it shows that it has an exotic modification.
[save_Isiro_1428629620890964174.zip](https://github.com/scardwell15/ExoticaTechnologies/files/8998472/save_Isiro_1428629620890964174.zip)

**Comment by scardwell15** [comment]
hello, i think i fixed this!
