### ISSUE TITLE
Iron Shell Upgrades Not Appearing

### ISSUE THREAD

**Issue by AmberTranscendence** [scardwell15/ExoticaTechnologies#3]
The new Iron Shell upgrade isn't showing up at all. I visit Exotica Tech branches and there's no option for Iron Shell upgrades.
None of the Iron Shell fleets spawning have the new upgrade either. 
I thought it might have been a mod conflict, so I started a new game with nothing, but Iron Shell and Exotica enabled and it was still the same result. Is this a bug or am I missing something?
Thanks.

**Comment by scardwell15** [comment]
fixed in latest
